// Additional products for seeding the database
export const additionalProducts = [
  // ==================== ELECTRONICS (20 more products) ====================
  {
    name: 'Smart Watch Pro',
    slug: 'smart-watch-pro',
    description: 'Advanced fitness tracking smartwatch with heart rate monitor, GPS, and 7-day battery life.',
    price: 129.99,
    comparePrice: 199.99,
    sku: 'ELEC-WATCH-002',
    inventory: 75,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80'],
    category: 'electronics',
    featured: true,
  },
  {
    name: '4K Webcam HD',
    slug: '4k-webcam-hd',
    description: 'Professional 4K webcam with auto-focus and built-in microphone for streaming and video calls.',
    price: 59.99,
    comparePrice: 99.99,
    sku: 'ELEC-CAM-003',
    inventory: 60,
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Wireless Keyboard & Mouse Combo',
    slug: 'wireless-keyboard-mouse-combo',
    description: 'Ergonomic wireless keyboard and mouse set with long battery life.',
    price: 45.99,
    comparePrice: null,
    sku: 'ELEC-KB-004',
    inventory: 100,
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Portable SSD 1TB',
    slug: 'portable-ssd-1tb',
    description: 'Ultra-fast 1TB portable SSD with USB-C connection and shock resistance.',
    price: 89.99,
    comparePrice: 129.99,
    sku: 'ELEC-SSD-005',
    inventory: 45,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Gaming Mouse RGB',
    slug: 'gaming-mouse-rgb',
    description: 'High-precision gaming mouse with customizable RGB lighting and 16000 DPI.',
    price: 59.99,
    comparePrice: 89.99,
    sku: 'ELEC-MOUSE-006',
    inventory: 80,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'USB-C Hub 7-in-1',
    slug: 'usbc-hub-7in1',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader, and power delivery.',
    price: 34.99,
    comparePrice: null,
    sku: 'ELEC-HUB-007',
    inventory: 120,
    images: ['https://images.unsplash.com/photo-1625948515291-69613efd103f?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Mechanical Keyboard RGB',
    slug: 'mechanical-keyboard-rgb',
    description: 'Premium mechanical keyboard with blue switches and customizable RGB backlighting.',
    price: 79.99,
    comparePrice: 119.99,
    sku: 'ELEC-KB-008',
    inventory: 55,
    images: ['https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&q=80'],
    category: 'electronics',
    featured: true,
  },
  {
    name: 'Wireless Earbuds Pro',
    slug: 'wireless-earbuds-pro',
    description: 'Premium wireless earbuds with active noise cancellation and 24-hour battery.',
    price: 89.99,
    comparePrice: 129.99,
    sku: 'ELEC-EAR-009',
    inventory: 90,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80'],
    category: 'electronics',
    featured: true,
  },
  {
    name: 'Phone Tripod Stand',
    slug: 'phone-tripod-stand',
    description: 'Adjustable phone tripod with remote shutter for photography and videos.',
    price: 24.99,
    comparePrice: null,
    sku: 'ELEC-TRIP-010',
    inventory: 150,
    images: ['https://images.unsplash.com/photo-1617886322207-6e9c3e8f4330?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Laptop Stand Aluminum',
    slug: 'laptop-stand-aluminum',
    description: 'Ergonomic aluminum laptop stand with adjustable height and cooling design.',
    price: 39.99,
    comparePrice: 59.99,
    sku: 'ELEC-STAND-011',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'External DVD Drive USB',
    slug: 'external-dvd-drive-usb',
    description: 'Slim external DVD/CD drive with USB 3.0 for laptops and desktops.',
    price: 29.99,
    comparePrice: null,
    sku: 'ELEC-DVD-012',
    inventory: 65,
    images: ['https://images.unsplash.com/photo-1625948515291-69613efd103f?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Bluetooth Speaker Waterproof',
    slug: 'bluetooth-speaker-waterproof',
    description: 'Portable waterproof Bluetooth speaker with 12-hour playtime and deep bass.',
    price: 49.99,
    comparePrice: 79.99,
    sku: 'ELEC-SPEAK-013',
    inventory: 85,
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'HD Monitor 27 inch',
    slug: 'hd-monitor-27-inch',
    description: '27-inch Full HD monitor with ultra-slim bezel and 75Hz refresh rate.',
    price: 139.99,
    comparePrice: 199.99,
    sku: 'ELEC-MON-014',
    inventory: 40,
    images: ['https://images.unsplash.com/photo-1527443195645-1133f7f28990?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Graphic Drawing Tablet',
    slug: 'graphic-drawing-tablet',
    description: 'Professional drawing tablet with pressure-sensitive pen for digital artists.',
    price: 64.99,
    comparePrice: 99.99,
    sku: 'ELEC-TAB-015',
    inventory: 50,
    images: ['https://images.unsplash.com/photo-1612832021895-3e8fb6c79a4f?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Smart LED Light Bulbs 4-Pack',
    slug: 'smart-led-light-bulbs-4pack',
    description: 'WiFi-enabled color-changing LED bulbs compatible with voice assistants.',
    price: 44.99,
    comparePrice: null,
    sku: 'ELEC-LED-016',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1580794843616-5926a62d99c5?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'USB Charging Cable 6ft 3-Pack',
    slug: 'usb-charging-cable-6ft-3pack',
    description: 'Durable braided USB-C charging cables, 6ft length, pack of 3.',
    price: 19.99,
    comparePrice: null,
    sku: 'ELEC-CABLE-017',
    inventory: 200,
    images: ['https://images.unsplash.com/photo-1625948515291-69613efd103f?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Phone Camera Lens Kit',
    slug: 'phone-camera-lens-kit',
    description: '5-in-1 clip-on camera lens kit for smartphones including macro and wide-angle.',
    price: 34.99,
    comparePrice: 49.99,
    sku: 'ELEC-LENS-018',
    inventory: 75,
    images: ['https://images.unsplash.com/photo-1606986628835-38b24b56e9bc?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Wireless Charging Pad',
    slug: 'wireless-charging-pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices.',
    price: 24.99,
    comparePrice: null,
    sku: 'ELEC-CHAR-019',
    inventory: 110,
    images: ['https://images.unsplash.com/photo-1591290619762-ac06b8e47f92?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Desktop Monitor Arm Mount',
    slug: 'desktop-monitor-arm-mount',
    description: 'Adjustable monitor arm mount with cable management for ergonomic viewing.',
    price: 69.99,
    comparePrice: 99.99,
    sku: 'ELEC-MOUNT-020',
    inventory: 45,
    images: ['https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },
  {
    name: 'Ring Light for Video',
    slug: 'ring-light-for-video',
    description: '10-inch LED ring light with tripod stand perfect for streaming and photography.',
    price: 39.99,
    comparePrice: 59.99,
    sku: 'ELEC-RING-021',
    inventory: 80,
    images: ['https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800&q=80'],
    category: 'electronics',
    featured: false,
  },

  // ==================== CLOTHING (20 more products) ====================
  {
    name: 'Men\'s Slim Fit Jeans',
    slug: 'mens-slim-fit-jeans',
    description: 'Classic slim fit jeans with stretch denim for comfort and style.',
    price: 49.99,
    comparePrice: 79.99,
    sku: 'CLOTH-JEANS-001',
    inventory: 100,
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Floral Summer Dress',
    slug: 'womens-floral-summer-dress',
    description: 'Light and breezy floral print dress perfect for summer occasions.',
    price: 54.99,
    comparePrice: null,
    sku: 'CLOTH-DRESS-002',
    inventory: 85,
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80'],
    category: 'clothing',
    featured: true,
  },
  {
    name: 'Men\'s Casual Button-Down Shirt',
    slug: 'mens-casual-button-down-shirt',
    description: 'Comfortable cotton button-down shirt in versatile colors.',
    price: 34.99,
    comparePrice: null,
    sku: 'CLOTH-SHIRT-003',
    inventory: 120,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Yoga Pants',
    slug: 'womens-yoga-pants',
    description: 'High-waisted yoga pants with moisture-wicking fabric and pockets.',
    price: 39.99,
    comparePrice: 54.99,
    sku: 'CLOTH-YOGA-004',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Men\'s Hoodie Sweatshirt',
    slug: 'mens-hoodie-sweatshirt',
    description: 'Cozy fleece-lined hoodie with kangaroo pocket and adjustable drawstring.',
    price: 44.99,
    comparePrice: null,
    sku: 'CLOTH-HOOD-005',
    inventory: 110,
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Leather Jacket',
    slug: 'womens-leather-jacket',
    description: 'Stylish faux leather jacket with zipper details and multiple pockets.',
    price: 69.99,
    comparePrice: 109.99,
    sku: 'CLOTH-JACK-006',
    inventory: 60,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80'],
    category: 'clothing',
    featured: true,
  },
  {
    name: 'Men\'s Athletic Shorts',
    slug: 'mens-athletic-shorts',
    description: 'Breathable athletic shorts with quick-dry fabric and zip pockets.',
    price: 29.99,
    comparePrice: null,
    sku: 'CLOTH-SHORT-007',
    inventory: 140,
    images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Knit Sweater',
    slug: 'womens-knit-sweater',
    description: 'Soft cable-knit sweater perfect for layering in cooler weather.',
    price: 49.99,
    comparePrice: 69.99,
    sku: 'CLOTH-SWEAT-008',
    inventory: 75,
    images: ['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Men\'s Polo Shirt',
    slug: 'mens-polo-shirt',
    description: 'Classic cotton polo shirt with ribbed collar and cuffs.',
    price: 32.99,
    comparePrice: null,
    sku: 'CLOTH-POLO-009',
    inventory: 130,
    images: ['https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Denim Jacket',
    slug: 'womens-denim-jacket',
    description: 'Vintage-style denim jacket with distressed details.',
    price: 59.99,
    comparePrice: 89.99,
    sku: 'CLOTH-DENIM-010',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Men\'s Chino Pants',
    slug: 'mens-chino-pants',
    description: 'Tailored chino pants in classic colors for versatile styling.',
    price: 44.99,
    comparePrice: null,
    sku: 'CLOTH-CHINO-011',
    inventory: 100,
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Maxi Skirt',
    slug: 'womens-maxi-skirt',
    description: 'Flowing maxi skirt with elastic waistband and side pockets.',
    price: 39.99,
    comparePrice: null,
    sku: 'CLOTH-SKIRT-012',
    inventory: 90,
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Men\'s Winter Coat',
    slug: 'mens-winter-coat',
    description: 'Insulated winter coat with detachable hood and multiple pockets.',
    price: 89.99,
    comparePrice: 139.99,
    sku: 'CLOTH-COAT-013',
    inventory: 50,
    images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Blazer',
    slug: 'womens-blazer',
    description: 'Professional tailored blazer perfect for office or formal occasions.',
    price: 59.99,
    comparePrice: 89.99,
    sku: 'CLOTH-BLAZ-014',
    inventory: 65,
    images: ['https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Men\'s Tank Top 3-Pack',
    slug: 'mens-tank-top-3pack',
    description: 'Comfortable cotton tank tops, pack of 3 in assorted colors.',
    price: 24.99,
    comparePrice: null,
    sku: 'CLOTH-TANK-015',
    inventory: 150,
    images: ['https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Cardigan',
    slug: 'womens-cardigan',
    description: 'Lightweight cardigan with button front and pockets.',
    price: 42.99,
    comparePrice: null,
    sku: 'CLOTH-CARD-016',
    inventory: 85,
    images: ['https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Men\'s Track Pants',
    slug: 'mens-track-pants',
    description: 'Comfortable track pants with elastic waist and zippered pockets.',
    price: 39.99,
    comparePrice: 54.99,
    sku: 'CLOTH-TRACK-017',
    inventory: 105,
    images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Jumpsuit',
    slug: 'womens-jumpsuit',
    description: 'Stylish one-piece jumpsuit with cinched waist and wide legs.',
    price: 64.99,
    comparePrice: 89.99,
    sku: 'CLOTH-JUMP-018',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Men\'s V-Neck Sweater',
    slug: 'mens-vneck-sweater',
    description: 'Classic v-neck sweater in soft cotton blend.',
    price: 44.99,
    comparePrice: null,
    sku: 'CLOTH-VNECK-019',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },
  {
    name: 'Women\'s Tunic Top',
    slug: 'womens-tunic-top',
    description: 'Loose-fit tunic top with flattering drape and side slits.',
    price: 34.99,
    comparePrice: null,
    sku: 'CLOTH-TUN-020',
    inventory: 110,
    images: ['https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=800&q=80'],
    category: 'clothing',
    featured: false,
  },

  // I'll continue with the remaining categories in the next part due to character limits
  // ==================== SHOES (20 more products) ====================
  {
    name: 'Running Shoes Men',
    slug: 'running-shoes-men',
    description: 'Lightweight running shoes with breathable mesh and cushioned sole.',
    price: 69.99,
    comparePrice: 99.99,
    sku: 'SHOE-RUN-022',
    inventory: 80,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'],
    category: 'shoes',
    featured: true,
  },
  {
    name: 'Women\'s Ankle Boots',
    slug: 'womens-ankle-boots',
    description: 'Stylish ankle boots with block heel and side zipper.',
    price: 79.99,
    comparePrice: 119.99,
    sku: 'SHOE-BOOT-002',
    inventory: 65,
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Men\'s Casual Loafers',
    slug: 'mens-casual-loafers',
    description: 'Comfortable slip-on loafers perfect for everyday wear.',
    price: 54.99,
    comparePrice: null,
    sku: 'SHOE-LOAF-003',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s Ballet Flats',
    slug: 'womens-ballet-flats',
    description: 'Classic ballet flats with cushioned insole in various colors.',
    price: 39.99,
    comparePrice: null,
    sku: 'SHOE-FLAT-004',
    inventory: 120,
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Men\'s Hiking Boots',
    slug: 'mens-hiking-boots',
    description: 'Waterproof hiking boots with ankle support and rugged sole.',
    price: 99.99,
    comparePrice: 149.99,
    sku: 'SHOE-HIKE-005',
    inventory: 55,
    images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s High Heels',
    slug: 'womens-high-heels',
    description: 'Elegant high heel pumps perfect for formal events.',
    price: 64.99,
    comparePrice: 94.99,
    sku: 'SHOE-HEEL-006',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Men\'s Dress Shoes',
    slug: 'mens-dress-shoes',
    description: 'Classic Oxford dress shoes with leather upper and cushioned insole.',
    price: 89.99,
    comparePrice: 129.99,
    sku: 'SHOE-DRESS-007',
    inventory: 60,
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s Sandals',
    slug: 'womens-sandals',
    description: 'Comfortable summer sandals with adjustable straps.',
    price: 34.99,
    comparePrice: null,
    sku: 'SHOE-SAND-008',
    inventory: 110,
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Men\'s Slip-On Sneakers',
    slug: 'mens-slipon-sneakers',
    description: 'Easy slip-on sneakers with memory foam insole.',
    price: 49.99,
    comparePrice: null,
    sku: 'SHOE-SLIP-009',
    inventory: 100,
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s Wedge Sandals',
    slug: 'womens-wedge-sandals',
    description: 'Platform wedge sandals with espadrille design.',
    price: 54.99,
    comparePrice: 79.99,
    sku: 'SHOE-WEDGE-010',
    inventory: 75,
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Men\'s Work Boots',
    slug: 'mens-work-boots',
    description: 'Steel-toe work boots with slip-resistant sole.',
    price: 109.99,
    comparePrice: 159.99,
    sku: 'SHOE-WORK-011',
    inventory: 50,
    images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s Running Shoes',
    slug: 'womens-running-shoes',
    description: 'Lightweight running shoes with responsive cushioning.',
    price: 74.99,
    comparePrice: 104.99,
    sku: 'SHOE-RUN-012',
    inventory: 85,
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80'],
    category: 'shoes',
    featured: true,
  },
  {
    name: 'Men\'s Canvas Sneakers',
    slug: 'mens-canvas-sneakers',
    description: 'Classic canvas sneakers in various colors.',
    price: 39.99,
    comparePrice: null,
    sku: 'SHOE-CANV-013',
    inventory: 130,
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s Knee-High Boots',
    slug: 'womens-kneehigh-boots',
    description: 'Fashionable knee-high boots with inner zipper.',
    price: 94.99,
    comparePrice: 139.99,
    sku: 'SHOE-KNEE-014',
    inventory: 55,
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Men\'s Flip Flops',
    slug: 'mens-flip-flops',
    description: 'Comfortable flip flops with arch support.',
    price: 19.99,
    comparePrice: null,
    sku: 'SHOE-FLIP-015',
    inventory: 150,
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s Espadrilles',
    slug: 'womens-espadrilles',
    description: 'Stylish espadrille flats with canvas upper.',
    price: 44.99,
    comparePrice: null,
    sku: 'SHOE-ESP-016',
    inventory: 90,
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Men\'s Basketball Shoes',
    slug: 'mens-basketball-shoes',
    description: 'High-top basketball shoes with ankle support and traction.',
    price: 84.99,
    comparePrice: 119.99,
    sku: 'SHOE-BASK-017',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s Mules',
    slug: 'womens-mules',
    description: 'Trendy backless mules with low heel.',
    price: 49.99,
    comparePrice: null,
    sku: 'SHOE-MULE-018',
    inventory: 80,
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Men\'s Boat Shoes',
    slug: 'mens-boat-shoes',
    description: 'Classic leather boat shoes with non-slip sole.',
    price: 64.99,
    comparePrice: 89.99,
    sku: 'SHOE-BOAT-019',
    inventory: 75,
    images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },
  {
    name: 'Women\'s Chelsea Boots',
    slug: 'womens-chelsea-boots',
    description: 'Versatile Chelsea boots with elastic side panels.',
    price: 69.99,
    comparePrice: 99.99,
    sku: 'SHOE-CHEL-020',
    inventory: 65,
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80'],
    category: 'shoes',
    featured: false,
  },

  // ==================== HOME & LIVING (20 more products) ====================
  {
    name: 'Memory Foam Pillow Set',
    slug: 'memory-foam-pillow-set',
    description: 'Set of 2 cooling memory foam pillows with bamboo cover.',
    price: 49.99,
    comparePrice: 79.99,
    sku: 'HOME-PILL-021',
    inventory: 90,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Ceramic Dinnerware Set 16-Piece',
    slug: 'ceramic-dinnerware-set-16piece',
    description: 'Complete dinnerware set for 4 with plates, bowls, and mugs.',
    price: 59.99,
    comparePrice: 89.99,
    sku: 'HOME-DINE-022',
    inventory: 60,
    images: ['https://images.unsplash.com/photo-1584990347449-39abeedb7584?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Throw Blanket Soft',
    slug: 'throw-blanket-soft',
    description: 'Ultra-soft fleece throw blanket in multiple colors.',
    price: 29.99,
    comparePrice: null,
    sku: 'HOME-BLANK-023',
    inventory: 120,
    images: ['https://images.unsplash.com/photo-1515260268569-9271009adfdb?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Wall Mirror Decorative',
    slug: 'wall-mirror-decorative',
    description: 'Round decorative wall mirror with metal frame.',
    price: 59.99,
    comparePrice: 89.99,
    sku: 'HOME-MIR-024',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1618220924273-338d82d6b886?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Kitchen Knife Set 15-Piece',
    slug: 'kitchen-knife-set-15piece',
    description: 'Professional kitchen knife set with wooden block.',
    price: 69.99,
    comparePrice: 109.99,
    sku: 'HOME-KNIFE-025',
    inventory: 55,
    images: ['https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Area Rug 5x7',
    slug: 'area-rug-5x7',
    description: 'Modern geometric pattern area rug, non-shed.',
    price: 79.99,
    comparePrice: 119.99,
    sku: 'HOME-RUG-026',
    inventory: 45,
    images: ['https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80'],
    category: 'home-living',
    featured: true,
  },
  {
    name: 'Storage Bins Set of 6',
    slug: 'storage-bins-set-of-6',
    description: 'Foldable fabric storage bins with handles.',
    price: 34.99,
    comparePrice: null,
    sku: 'HOME-STOR-027',
    inventory: 100,
    images: ['https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Table Lamp Modern',
    slug: 'table-lamp-modern',
    description: 'Contemporary table lamp with adjustable brightness.',
    price: 44.99,
    comparePrice: 64.99,
    sku: 'HOME-LAMP-028',
    inventory: 85,
    images: ['https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Cookware Set Non-Stick',
    slug: 'cookware-set-nonstick',
    description: '10-piece non-stick cookware set with lids.',
    price: 89.99,
    comparePrice: 139.99,
    sku: 'HOME-COOK-029',
    inventory: 50,
    images: ['https://images.unsplash.com/photo-1585619443477-419c0e95bfae?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Curtain Panels Blackout',
    slug: 'curtain-panels-blackout',
    description: 'Energy-efficient blackout curtain panels, set of 2.',
    price: 39.99,
    comparePrice: null,
    sku: 'HOME-CURT-030',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1591088426959-3da8a38377d1?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Coffee Table Wooden',
    slug: 'coffee-table-wooden',
    description: 'Rustic wooden coffee table with lower shelf.',
    price: 109.99,
    comparePrice: 169.99,
    sku: 'HOME-TABLE-031',
    inventory: 35,
    images: ['https://images.unsplash.com/photo-1532372576444-dda954194ad0?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Bathroom Organizer Set',
    slug: 'bathroom-organizer-set',
    description: 'Complete bathroom organization set with shelves and bins.',
    price: 54.99,
    comparePrice: 79.99,
    sku: 'HOME-BATH-032',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Plant Pots Set of 4',
    slug: 'plant-pots-set-of-4',
    description: 'Ceramic indoor plant pots with drainage holes.',
    price: 29.99,
    comparePrice: null,
    sku: 'HOME-POT-033',
    inventory: 110,
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Desk Organizer Bamboo',
    slug: 'desk-organizer-bamboo',
    description: 'Eco-friendly bamboo desk organizer with compartments.',
    price: 34.99,
    comparePrice: null,
    sku: 'HOME-DESK-034',
    inventory: 80,
    images: ['https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Shower Curtain Set',
    slug: 'shower-curtain-set',
    description: 'Waterproof fabric shower curtain with hooks included.',
    price: 24.99,
    comparePrice: null,
    sku: 'HOME-SHOW-035',
    inventory: 105,
    images: ['https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Wall Clock Modern',
    slug: 'wall-clock-modern',
    description: 'Silent wall clock with minimalist design.',
    price: 32.99,
    comparePrice: null,
    sku: 'HOME-CLOCK-036',
    inventory: 90,
    images: ['https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Bedding Set Queen',
    slug: 'bedding-set-queen',
    description: 'Luxury microfiber bedding set with duvet cover and pillowcases.',
    price: 69.99,
    comparePrice: 99.99,
    sku: 'HOME-BED-037',
    inventory: 65,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Trash Can Stainless',
    slug: 'trash-can-stainless',
    description: 'Step-on trash can with soft-close lid and liner pocket.',
    price: 59.99,
    comparePrice: 84.99,
    sku: 'HOME-TRASH-038',
    inventory: 75,
    images: ['https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Bath Towel Set',
    slug: 'bath-towel-set',
    description: 'Ultra-absorbent cotton bath towel set of 6.',
    price: 44.99,
    comparePrice: null,
    sku: 'HOME-TOWEL-039',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1600429183412-e8e2e468e43c?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },
  {
    name: 'Bookshelf 5-Tier',
    slug: 'bookshelf-5tier',
    description: 'Wooden 5-tier bookshelf with modern design.',
    price: 89.99,
    comparePrice: 129.99,
    sku: 'HOME-BOOK-040',
    inventory: 50,
    images: ['https://images.unsplash.com/photo-1594620302200-9a762244a156?w=800&q=80'],
    category: 'home-living',
    featured: false,
  },

  // ==================== BEAUTY (20 more products) ====================
  {
    name: 'Facial Cleanser Set',
    slug: 'facial-cleanser-set',
    description: 'Complete facial cleansing set with morning and night formulas.',
    price: 34.99,
    comparePrice: 49.99,
    sku: 'BEAUTY-CLEAN-021',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Makeup Brush Set Professional',
    slug: 'makeup-brush-set-professional',
    description: '12-piece professional makeup brush set with case.',
    price: 44.99,
    comparePrice: 69.99,
    sku: 'BEAUTY-BRUSH-022',
    inventory: 85,
    images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=80'],
    category: 'beauty',
    featured: true,
  },
  {
    name: 'Vitamin C Serum',
    slug: 'vitamin-c-serum',
    description: 'Brightening vitamin C serum with hyaluronic acid.',
    price: 29.99,
    comparePrice: null,
    sku: 'BEAUTY-SERUM-023',
    inventory: 110,
    images: ['https://images.unsplash.com/photo-1620916297893-e814c6be3952?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Eye Shadow Palette',
    slug: 'eye-shadow-palette',
    description: '35-color eyeshadow palette with matte and shimmer shades.',
    price: 39.99,
    comparePrice: 59.99,
    sku: 'BEAUTY-EYE-024',
    inventory: 75,
    images: ['https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Moisturizing Face Cream',
    slug: 'moisturizing-face-cream',
    description: 'Deep hydrating face cream for all skin types.',
    price: 32.99,
    comparePrice: null,
    sku: 'BEAUTY-CREAM-025',
    inventory: 100,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Lip Gloss Set',
    slug: 'lip-gloss-set',
    description: 'Set of 6 high-shine lip glosses in various shades.',
    price: 24.99,
    comparePrice: null,
    sku: 'BEAUTY-LIP-026',
    inventory: 120,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Hair Straightener Ceramic',
    slug: 'hair-straightener-ceramic',
    description: 'Professional ceramic hair straightener with adjustable heat.',
    price: 54.99,
    comparePrice: 79.99,
    sku: 'BEAUTY-HAIR-027',
    inventory: 65,
    images: ['https://images.unsplash.com/photo-1526045478516-99145907023c?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Nail Polish Set',
    slug: 'nail-polish-set',
    description: '12-piece nail polish collection with trending colors.',
    price: 34.99,
    comparePrice: null,
    sku: 'BEAUTY-NAIL-028',
    inventory: 90,
    images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Face Mask Sheet Pack',
    slug: 'face-mask-sheet-pack',
    description: 'Variety pack of 10 hydrating sheet masks.',
    price: 19.99,
    comparePrice: null,
    sku: 'BEAUTY-MASK-029',
    inventory: 130,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Eyeliner Pen Waterproof',
    slug: 'eyeliner-pen-waterproof',
    description: 'Long-lasting waterproof liquid eyeliner pen.',
    price: 14.99,
    comparePrice: null,
    sku: 'BEAUTY-LINE-030',
    inventory: 140,
    images: ['https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Skincare Routine Kit',
    slug: 'skincare-routine-kit',
    description: 'Complete 5-step skincare routine for morning and night.',
    price: 79.99,
    comparePrice: 119.99,
    sku: 'BEAUTY-KIT-031',
    inventory: 60,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    category: 'beauty',
    featured: true,
  },
  {
    name: 'Blush Palette',
    slug: 'blush-palette',
    description: '6-color blush palette with matte and shimmer finishes.',
    price: 27.99,
    comparePrice: null,
    sku: 'BEAUTY-BLUSH-032',
    inventory: 85,
    images: ['https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Hair Dryer Professional',
    slug: 'hair-dryer-professional',
    description: 'Ionic hair dryer with diffuser and concentrator attachments.',
    price: 64.99,
    comparePrice: 94.99,
    sku: 'BEAUTY-DRY-033',
    inventory: 55,
    images: ['https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Makeup Remover Wipes',
    slug: 'makeup-remover-wipes',
    description: 'Gentle makeup remover wipes, pack of 100.',
    price: 12.99,
    comparePrice: null,
    sku: 'BEAUTY-WIPE-034',
    inventory: 150,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Foundation Full Coverage',
    slug: 'foundation-full-coverage',
    description: 'Long-wear full coverage foundation in multiple shades.',
    price: 39.99,
    comparePrice: 54.99,
    sku: 'BEAUTY-FOUND-035',
    inventory: 80,
    images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Mascara Volumizing',
    slug: 'mascara-volumizing',
    description: 'Volumizing mascara with curved brush for dramatic lashes.',
    price: 18.99,
    comparePrice: null,
    sku: 'BEAUTY-MASC-036',
    inventory: 105,
    images: ['https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Perfume Gift Set',
    slug: 'perfume-gift-set',
    description: 'Mini perfume collection gift set with 5 popular fragrances.',
    price: 49.99,
    comparePrice: 74.99,
    sku: 'BEAUTY-PERF-037',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Exfoliating Face Scrub',
    slug: 'exfoliating-face-scrub',
    description: 'Gentle exfoliating face scrub with natural ingredients.',
    price: 22.99,
    comparePrice: null,
    sku: 'BEAUTY-SCRUB-038',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Curling Iron Ceramic',
    slug: 'curling-iron-ceramic',
    description: 'Ceramic curling iron with adjustable temperature control.',
    price: 44.99,
    comparePrice: 64.99,
    sku: 'BEAUTY-CURL-039',
    inventory: 60,
    images: ['https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },
  {
    name: 'Sunscreen SPF 50',
    slug: 'sunscreen-spf-50',
    description: 'Lightweight broad-spectrum sunscreen for face and body.',
    price: 24.99,
    comparePrice: null,
    sku: 'BEAUTY-SUN-040',
    inventory: 115,
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
    category: 'beauty',
    featured: false,
  },

  // ==================== SPORTS (20 more products) ====================
  {
    name: 'Yoga Mat Premium',
    slug: 'yoga-mat-premium',
    description: 'Extra-thick yoga mat with carrying strap and non-slip surface.',
    price: 34.99,
    comparePrice: 49.99,
    sku: 'SPORT-YOGA-021',
    inventory: 100,
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Resistance Bands Set',
    slug: 'resistance-bands-set',
    description: 'Set of 5 resistance bands with different resistance levels.',
    price: 24.99,
    comparePrice: null,
    sku: 'SPORT-BAND-022',
    inventory: 120,
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Jump Rope Speed',
    slug: 'jump-rope-speed',
    description: 'Adjustable speed jump rope with ball bearings for smooth rotation.',
    price: 16.99,
    comparePrice: null,
    sku: 'SPORT-ROPE-023',
    inventory: 140,
    images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Water Bottle Insulated',
    slug: 'water-bottle-insulated',
    description: 'Stainless steel insulated water bottle keeps drinks cold for 24 hours.',
    price: 27.99,
    comparePrice: null,
    sku: 'SPORT-WATER-024',
    inventory: 130,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Kettlebell 20lb',
    slug: 'kettlebell-20lb',
    description: 'Cast iron kettlebell with wide handle for two-handed exercises.',
    price: 39.99,
    comparePrice: 54.99,
    sku: 'SPORT-KETTLE-025',
    inventory: 70,
    images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Gym Bag Duffel',
    slug: 'gym-bag-duffel',
    description: 'Spacious gym duffel bag with shoe compartment and wet pocket.',
    price: 44.99,
    comparePrice: 64.99,
    sku: 'SPORT-BAG-026',
    inventory: 85,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Foam Roller Muscle',
    slug: 'foam-roller-muscle',
    description: 'High-density foam roller for muscle recovery and massage.',
    price: 29.99,
    comparePrice: null,
    sku: 'SPORT-FOAM-027',
    inventory: 95,
    images: ['https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Basketball Official Size',
    slug: 'basketball-official-size',
    description: 'Official size basketball with superior grip and durability.',
    price: 34.99,
    comparePrice: null,
    sku: 'SPORT-BALL-028',
    inventory: 80,
    images: ['https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Tennis Racket Pro',
    slug: 'tennis-racket-pro',
    description: 'Lightweight tennis racket with oversized head for power.',
    price: 59.99,
    comparePrice: 89.99,
    sku: 'SPORT-TENNIS-029',
    inventory: 50,
    images: ['https://images.unsplash.com/photo-1622279457486-62dda4345e4a?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Exercise Bike Stationary',
    slug: 'exercise-bike-stationary',
    description: 'Indoor stationary bike with adjustable seat and digital monitor.',
    price: 229.99,
    comparePrice: 329.99,
    sku: 'SPORT-BIKE-030',
    inventory: 30,
    images: ['https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&q=80'],
    category: 'sports',
    featured: true,
  },
  {
    name: 'Yoga Blocks Set',
    slug: 'yoga-blocks-set',
    description: 'Set of 2 high-density foam yoga blocks for support.',
    price: 19.99,
    comparePrice: null,
    sku: 'SPORT-BLOCK-031',
    inventory: 110,
    images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Pull-Up Bar Doorway',
    slug: 'pullup-bar-doorway',
    description: 'Adjustable doorway pull-up bar with multiple grip positions.',
    price: 34.99,
    comparePrice: 49.99,
    sku: 'SPORT-PULL-032',
    inventory: 75,
    images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Boxing Gloves Training',
    slug: 'boxing-gloves-training',
    description: 'Professional boxing gloves with wrist support.',
    price: 49.99,
    comparePrice: 74.99,
    sku: 'SPORT-BOX-033',
    inventory: 65,
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Soccer Ball Official',
    slug: 'soccer-ball-official',
    description: 'Official size and weight soccer ball with durable construction.',
    price: 29.99,
    comparePrice: null,
    sku: 'SPORT-SOCCER-034',
    inventory: 90,
    images: ['https://images.unsplash.com/photo-1614632537423-1e8babc1963d?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Treadmill Folding',
    slug: 'treadmill-folding',
    description: 'Space-saving folding treadmill with LCD display.',
    price: 349.99,
    comparePrice: 499.99,
    sku: 'SPORT-TREAD-035',
    inventory: 25,
    images: ['https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&q=80'],
    category: 'sports',
    featured: true,
  },
  {
    name: 'Bicycle Helmet Adult',
    slug: 'bicycle-helmet-adult',
    description: 'Adjustable cycling helmet with ventilation and LED light.',
    price: 39.99,
    comparePrice: 59.99,
    sku: 'SPORT-HELM-036',
    inventory: 80,
    images: ['https://images.unsplash.com/photo-1573755503908-790f47c86ceb?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Swim Goggles Anti-Fog',
    slug: 'swim-goggles-antifog',
    description: 'Anti-fog swimming goggles with UV protection.',
    price: 19.99,
    comparePrice: null,
    sku: 'SPORT-SWIM-037',
    inventory: 105,
    images: ['https://images.unsplash.com/photo-1576356183200-b3404d8f69c5?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Ab Wheel Roller',
    slug: 'ab-wheel-roller',
    description: 'Dual ab wheel roller with knee pad for core training.',
    price: 22.99,
    comparePrice: null,
    sku: 'SPORT-AB-038',
    inventory: 100,
    images: ['https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Badminton Set Complete',
    slug: 'badminton-set-complete',
    description: 'Complete badminton set with 4 rackets, shuttlecocks, and net.',
    price: 59.99,
    comparePrice: 89.99,
    sku: 'SPORT-BAD-039',
    inventory: 55,
    images: ['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
  {
    name: 'Protein Shaker Bottle',
    slug: 'protein-shaker-bottle',
    description: 'Leak-proof shaker bottle with mixing ball and measurement marks.',
    price: 14.99,
    comparePrice: null,
    sku: 'SPORT-SHAKE-040',
    inventory: 125,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80'],
    category: 'sports',
    featured: false,
  },
]
